export const links = {
  home: 'https://www.hyperlane.xyz',
  explorer: 'https://explorer.hyperlane.xyz',
  discord: 'https://discord.gg/VK9ZUy3aTV',
  github: 'https://github.com/hyperlane-xyz/hyperlane-warp-ui-template',
  docs: 'https://docs.hyperlane.xyz',
  registry: 'https://github.com/hyperlane-xyz/hyperlane-registry',
  cliDocs: 'https://docs.hyperlane.xyz/docs/reference/cli',
  gasDocs: 'https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas',
  ismDocs: 'https://docs.hyperlane.xyz/docs/protocol/ISM/modular-security',
  warpDocs: 'https://docs.hyperlane.xyz/docs/protocol/warp-routes/warp-routes-overview',
  warpUiDocs: 'https://docs.hyperlane.xyz/docs/guides/deploy-warp-route-UI',
  chains: 'https://docs.hyperlane.xyz/docs/resources/domains',
  twitter: 'https://x.com/hyperlane',
  blog: 'https://medium.com/hyperlane',
  tos: 'https://hyperlane.xyz/terms-of-service',
  privacyPolicy: 'https://hyperlane.xyz/privacy-policy',
  bounty:
    'https://github.com/search?q=org:hyperlane-xyz+label:bounty+is:open+is:issue&type=issues&s=&o=desc',
  coinGecko: 'https://www.coingecko.com/',
};
